# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: William Jiao's Portfolio # This is what shows up in the tab of the browser


# Hero Section
name: William Jiao
headline: Hello, I am William Jiao! Nice to meet you! 
description: >- # dont remove this line. this will ignore all new lines until the next section
  I am William Jiao, a current third year at UC Davis, who loves all things related to electrical engineering, especially automotive!
  My love for engineering started when I checked out the booth for Formula Racing at UC Davis, the Davis FSAE EEV team during orientation,
  falling in love with the beauty of the engineering that goes into making functioning vehicles we take for granted, from 
  systems as large as the tractive battery to ones as small as crash sensors. I hope to continue growing my passion for engineering as 
  I keep increasing my book knowledge at school, and I aspire to use my accumulated knowledge and experience to change the world for the 
  better as an engineer! 


# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url:  /assets/resume/Resume_3.pdf

# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: www.linkedin.com/in/williambjiao    # https://www.linkedin.com/in/{your url slug} 
  github: https://github.com/WillyWonky967    # https://github.com/{your url slug}     
  discord: simpofsokomoki
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: PCB Design Tools
    tools:
    - name: Altium 
      desc: "Created impedance matched ethernet PCBs for data collection and PCBs to handle high voltage power electronics for the UC Davis FSAE team"
    - name: KiCad
      desc: "Can use KiCAD in addition to Altium Designer for PCB design"
  - category: Prototyping Tools
    tools:
    - name: RapidHarness 
      desc: "Laid out LV and HV wiring harness schematic using RapidHarness, which was used in assmbling an FSAE racecar's wiring harness"
    - name: LTSpice 
      desc: "Simulated circuits used in PCB designs and in testing setups using LTSpice to validate electrical function"
    - name: SolidWorks 
      desc: "Opened and validated enclosures for low voltage electronics packaging"
  - category: Programming Languages
    tools:
    - name: C
      desc: "Used to program STM32 and Arduino microcontrollers to send and collect data over CAN, I2C and SPI within an FSAE racecar and in testing setups"
    - name: C++ 
      desc: "Programmed sorting algorithms in C++ to parse data"
    - name: MATLAB
      desc: "Used MATLAB to write and represent fourier transforms and to calculate systems of equations for coursework"
    - name: Python 
      desc: "Used Python to run scripts to parse through files of data to find data values"
    - name: Java 
      desc: "General Java knowledge of Java for writing algorithms and for importing mods in Minecraft"
    - name: Verilog 
      desc: "Programmed a pipelined matrix multiplier using Verilog, which was for a course assignment"
  - category: Electronic Testing Tools
    tools:
    -  name: Oscilloscope 
       desc: "Use oscilloscopes to view waveforms and timing of circuits during circuit debugging process"
    -  name: Multimeter 
       desc: "Measured voltages and resistances of circuit paths to check for impedance and voltages, and checked for connectivity between connections during debugging"
  - category: PCB Design
    tools:
    - name: Altium Designer 
      desc: "Created schematics and layouts for various PCBs using Altium, and used Gerber files from Altium to manufacture PCBs"
    - name: KiCAD
      desc: "Created PCBs using KiCAD as well, but mostly used Altium Designer"
  - category: Development / Data Acquisition Tools 
    tools: 
    - name: GIT 
      desc: "Used GIT version control to push firmware and PCB changes to Github and to Altium365, and to clone code from Github"
    - name: UNIX Terminal
      desc: "Used UNIX terminal to use shell scripting commands and to use GIT version control across workspaces"
    - name: CAN
      desc: "Used CAN bus to transmit data across car, used CAN order/ID, and message frequency to determine CAN bus load and better acquire data"
# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
